import { isWeb } from '@monorepo/function-shares';
import dynamic from 'next/dynamic';
import Home from './home';
import Head from 'next/head';

const App = dynamic(() => import('./AppShell'), {
  ssr: false,
});

export default function Index() {
  return isWeb ? (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />{' '}
    </>
  ) : (
    <App />
  );
}
