import { AppProps } from 'next/app';
import Head from 'next/head';
import './styles.css';

function CustomApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="target-densitydpi=device-dpi, initial-scale=1.0, user-scalable=no"
        />
        <meta property="og:title" content={"test"} key="title" />
        <meta property="og:description" content={"test cái"} />
        <meta
          property="og:image"
          content={
            "https://play-lh.googleusercontent.com/4muB4i5PE_vT7ZcTMvEHFSzwfDEjrL04-MuXDZMpgNtfqGtw3i06gzDBfePkJqa9na8"
          }
        />
      </Head>
      <main className="app">
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default CustomApp;
