name: Consumer Web on Dev

on: workflow_dispatch

jobs:
  build:
    name: Deploy consumer web on dev
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: subdir/yarn.lock

      - name: Install dependencies & export
        run: |
          npm install -g yarn
          yarn install
          # echo NEXT_PUBLIC_API_SERVER='"$API_ENDPOINT"' >> .env.local
          # echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID_DEV }}" >> .env.local
          yarn consumer:build
