name: Consumer Web on Dev

env:
  # S3_BUCKET: mio-admin-static-website-dev
  API_ENDPOINT: https://dev-api.itaphoa.com
  # DISTRIBUTION: E33KCKRHW9UGRM
  TELEGRAM_TO: -563879366
  TELEGRAM_TOKEN: 1914674250:AAFGBB_ZRxaagWaCDiIhv6f_aqaBGKk8FL0
  # BUILD_ENV: dev

on: workflow_dispatch

jobs:
  build:
    name: Deploy consumer web on dev
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies & export
        run: |
          npm install -g yarn
          yarn install
          echo NEXT_PUBLIC_API_SERVER='"$NX_DOMAIN"' >> .env.local
          yarn consumer:build
      
      - name: Send tele message
        continue-on-error: true
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ env.TELEGRAM_TOKEN }}
          format: markdown
          if: ${{ job.status }} != 'success'
          message: |
            ========
            Lỗi rồi, ối dồi ôi
          if: ${{ job.status }} == 'success'      
          message: |
            ========
            env dev -- test from Loi
            🚀 **${{ github.actor }}** - ${{ github.workflow }} => **${{ job.status }}**
            Branch: ${{github.ref}} SHA: ${{ env.SHORT_SHA }} ENV: ${{env.BUILD_ENV}}
      
